### PR TITLE
Correct spelling error in documentation.

### PR DESCRIPTION
**Pull request by derekmahar**

### CODE REVIEW

**Comment by waralex** [comment]
@derekmahar Thanks a lot. I plan to return to active development of this package within a month or two. I'm wondering if you've tried using it and what your impressions are if you have

**Comment by derekmahar** [comment]
@waralex Thank you for creating DataFramesDB.  I think this is a highly worthwhile project.  The package caught my attention when I searched for DataFrames in the Julia Discourse.  I'm afraid, though, that I haven't yet tried it because I'm still very new to Julia and haven't yet even experimented much with [DataFrames.jl](https://juliadata.github.io/DataFrames.jl/stable/).  Does DataFramesDB support column indexes or is this one of your planned features?

**Comment by waralex** [comment]
Indexes for columnar databases are quite a debatable thing. Especially, classical indexes in the form of trees. I was thinking about an index based on the bloom filter, which would allow you to quickly determine whether a block of 64,000 records has the desired ones and whether it is worth reading from the disk, unarchiving and checking each record for compliance. But this is one of the future plans.

**Comment by derekmahar** [comment]
I have no experience with columnar databases, but am interested to learn more.  Your [reference](https://discourse.julialang.org/t/ann-dataframedbs-jl/35718/5?u=derekmahar) to [ClickHouse](https://clickhouse.tech/) was my first encounter with this database.

Assuming you can still exclude any false positives using a secondary filter, I think a [bloom filter](https://en.wikipedia.org/wiki/Bloom_filter) index would be a clever alternative to a tree structure index.  Is this idea of a secondary filter what you mean by "checking each record for compliance"?

**Comment by derekmahar** [comment]
Based on [_Why do you use JuliaDB?_](https://discourse.julialang.org/t/why-do-you-use-juliadb/30410), there still seems to be a need for a database implemented in Julia for processing very large data sets.  This may be a great opportunity for DataFramesDB.

**Comment by waralex** [comment]
>Is this idea of a secondary filter what you mean by "checking each record for compliance"?

Yes, In other words, the bloom filter determines whether a large block of records can contain the desired ones. And if it can, the block is loaded and each entry in it is checked for compliance with the selection condition. I can also create a primary index for the entire table (i.e. just sort it by a column or set of columns). Secondary indexes, which usually represent the "secondary index"->"primary index" correspondence, are quite meaningless for column database tasks. Columnar databases are designed for requesting a large amount of data, i.e. primarily for statistical and analytical tasks. They are not effective for point requests and lose out to with classic databases in this tasks.

**Comment by waralex** [comment]
>This may be an opportunity for DataFramesDB.

Yes, this is the niche I want to occupy :) The problem is that I was overloaded at my main job, plus the guys from plotly offered to develop a backend for Dash for them. Therefore, I had to freeze development, although this is the most interesting project for me personally.

**Comment by derekmahar** [comment]
I understand how responsibilities can interfere with one's hobbies. :)

I look forward to seeing what you do next with DataFramesDB.  In the meantime, I'll continue to study Julia and experiment with packages like [CSV.jl](https://juliadata.github.io/CSV.jl/stable/), [DataFrames.jl](http://juliadata.github.io/DataFrames.jl/stable/), and [DataFramesDB.jl](https://waralex.github.io/DataFrameDBs.jl/dev/).

**Comment by waynelapierre** [comment]
JuliaDB is quite unusable now. I look forward to seeing DataFramesDB succeed.

**Pull request merged**
